change

diff --git a/10.1/s2i/bin/assemble b/10.1/s2i/bin/assemble
--- a/10.1/s2i/bin/assemble
+++ b/10.1/s2i/bin/assemble
@@ -2,15 +2,55 @@
 
 PID_FILE=/tmp/wildfly.pid
 
-JBOSS_HOME=/wildfly
-JBOSS_CLI=$JBOSS_HOME/bin/jboss-cli.sh
-JBOSS_MODE=${1:-"standalone"}
-JBOSS_CONFIG=${2:-"$JBOSS_MODE.xml"}
-
 function wait_for_server() {
-  until `$JBOSS_CLI -u=$ADMIN -p=$PASSWORD -c ":read-attribute(name=server-state)" 2> /dev/null | grep -q running`; do
+  until `/wildfly/bin/jboss-cli.sh -u=$ADMIN -p=$PASSWORD -c ":read-attribute(name=server-state)" 2> /dev/null | grep -q running`; do
     sleep 1
   done
+}
+
+function keycloak_config() {
+  echo "Cheching variables Keycloak"
+  
+  if [ -n "$WAR_NAME" ] && [ -n "$KEYCLOAK_SECURE_DEPLOYMENT_ATTRS" ]
+  then
+    # add admin user
+    /wildfly/bin/add-user.sh $ADMIN $PASSWORD --silent
+
+    #echo "Starting wildfly for deployment"
+    /wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &
+    echo $! > ${PID_FILE}
+
+    rc=0
+    ishttpup || rc=$?
+    if [ $rc -eq 1 ]; then
+      echo "Timed out waiting for http listening port for wildfly process"
+      exit 1
+    elif [ $rc -eq 2 ]; then
+      echo "wildfly process failed to start"
+      exit 2
+    fi
+
+    echo "=> Executing the commands"
+    echo "=> WAR_NAME (war that will be secured): " $WAR_NAME
+    echo "=> KEYCLOAK_SECURE_DEPLOYMENT_ATTRS (secure deployment params): " $KEYCLOAK_SECURE_DEPLOYMENT_ATTRS
+
+    /wildfly/bin/jboss-cli.sh -c -u=$ADMIN -p=$PASSWORD << EOF
+batch
+
+# Add Keycloak Secure Deployment
+/subsystem=keycloak/secure-deployment=$WAR_NAME.war:add($KEYCLOAK_SECURE_DEPLOYMENT_ATTRS)
+
+# Execute the batch
+run-batch
+EOF
+
+    echo "=> Shutting down WildFly"
+    /wildfly/bin/jboss-cli.sh -u=$ADMIN -p=$PASSWORD -c ":shutdown"
+    rm /tmp/wildfly.pid
+
+    # remove admin user
+    sed -i '/^#/! s/^/#/' /wildfly/{standalone,domain}/configuration/mgmt-{groups,users}.properties
+  fi
 }
 
 # restore maven dependencies downloaded in a previous build,
@@ -222,48 +262,8 @@ function move_artifacts() {
 ADMIN=admin
 PASSWORD=passw0rd_
 
-
-
 # Keycloak
-echo "Cheching variables Keycloak"
-echo "=> WAR_NAME (secure deployment): " $WAR_NAME
-echo "=> KEYCLOAK_SECURE_DEPLOYMENT_ATTRS (secure deployment): " $KEYCLOAK_SECURE_DEPLOYMENT_ATTRS
-
-if [ -n "$WAR_NAME" ] && [ -n "$KEYCLOAK_SECURE_DEPLOYMENT_ATTRS" ]
-then
-  echo "Starting to configure keycloak subsystem"
-
-  $JBOSS_HOME/bin/add-user.sh $ADMIN $PASSWORD --silent
-
-  echo "=> Starting WildFly server"
-  $JBOSS_HOME/bin/$JBOSS_MODE.sh -b 0.0.0.0 -c $JBOSS_CONFIG &
-
-  echo "=> Waiting for the server to boot"
-  wait_for_server
-
-  echo "=> Executing the commands"
-  echo "=> WAR_NAME (secure deployment): " $WAR_NAME
-  echo "=> KEYCLOAK_SECURE_DEPLOYMENT_ATTRS (secure deployment): " $KEYCLOAK_SECURE_DEPLOYMENT_ATTRS
-
-  $JBOSS_CLI -c -u=$ADMIN -p=$PASSWORD << EOF
-batch
-
-# Add Keycloak Secure Deployment
-/subsystem=keycloak/secure-deployment=$WAR_NAME.war:add($KEYCLOAK_SECURE_DEPLOYMENT_ATTRS)
-
-# Execute the batch
-run-batch
-EOF
-
-  echo "=> Shutting down WildFly"
-  if [ "$JBOSS_MODE" = "standalone" ]; then
-    $JBOSS_CLI -c -u=$ADMIN -p=$PASSWORD ":shutdown"
-  else
-    $JBOSS_CLI -c -u=$ADMIN -p=$PASSWORD "/host=*:shutdown"
-  fi
-fi
-
-
+keycloak_config
 
 # Source code provided to S2I is at ${HOME}
 LOCAL_SOURCE_DIR=${HOME}
@@ -325,7 +325,7 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
     fi
   fi
 
-  # Append user provided args
+  # Append user provided args
   if [ -n "$MAVEN_ARGS_APPEND" ]; then
     export MAVEN_ARGS="$MAVEN_ARGS $MAVEN_ARGS_APPEND"
   fi
